export const P21_TEST = {
    IlluminateCompLight: false,
    ProgramD1: '2',
    ProgramD2: '1',
    VerbD1: '0',
    VerbD2: '6',
    NounD1: '4',
    NounD2: '3',
    Register1Sign:'-',
    Register1D1: '0',
    Register1D2: '0',
    Register1D3: '9',
    Register1D4: '2',
    Register1D5: '2',
    Register2Sign:'-',
    Register2D1: '1',
    Register2D2: '7',
    Register2D3: '5',
    Register2D4: '6',
    Register2D5: '1',
    Register3Sign:'+',
    Register3D1: '0',
    Register3D2: '0',
    Register3D3: '6',
    Register3D4: '0',
    Register3D5: '8',
}

export const OFF_TEST = {
    IlluminateCompLight: false,
    ProgramD1: '',
    ProgramD2: '',
    VerbD1: '',
    VerbD2: '',
    NounD1: '',
    NounD2: '',
    Register1Sign:'',
    Register1D1: '',
    Register1D2: '',
    Register1D3: '',
    Register1D4: '',
    Register1D5: '',
    Register2Sign:'',
    Register2D1: '',
    Register2D2: '',
    Register2D3: '',
    Register2D4: '',
    Register2D5: '',
    Register3Sign:'',
    Register3D1: '',
    Register3D2: '',
    Register3D3: '',
    Register3D4: '',
    Register3D5: '',
}
