-d E:\OneDrive\Proyectos\DSKY\Firmware\TangNano9KTestLCD\impl\gwsynthesis\Tang_nano_9K_LCD.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\OneDrive\Proyectos\DSKY\Firmware\TangNano9KTestLCD\src\Tang_nano_9K_LCD.cst
-cfg E:\OneDrive\Proyectos\DSKY\Firmware\TangNano9KTestLCD\impl\pnr\device.cfg
-sdc E:\OneDrive\Proyectos\DSKY\Firmware\TangNano9KTestLCD\src\Tang_nano_9K_LCD.sdc
-bit
-tr
-ph
-timing
-correct_hold 1
-route_maxfan 23
