export const V35_TEST = {
    IlluminateCompLight: true,
    ProgramD1: '8',
    ProgramD2: '8',
    VerbD1: '8',
    VerbD2: '8',
    NounD1: '8',
    NounD2: '8',
    Register1Sign:'+',
    Register1D1: '8',
    Register1D2: '8',
    Register1D3: '8',
    Register1D4: '8',
    Register1D5: '8',
    Register2Sign:'+',
    Register2D1: '8',
    Register2D2: '8',
    Register2D3: '8',
    Register2D4: '8',
    Register2D5: '8',
    Register3Sign:'+',
    Register3D1: '8',
    Register3D2: '8',
    Register3D3: '8',
    Register3D4: '8',
    Register3D5: '8',
    IlluminateUplinkActy: 1, 
    IlluminateNoAtt: 1,
    IlluminateStby: 1,
    IlluminateKeyRel: 1,
    IlluminateOprErr: 1, 
    IlluminateNoDap: 1,
    IlluminatePrioDisp: 1,
    IlluminateTemp: 1,
    IlluminateGimbalLock: 1,
    IlluminateProg: 1,
    IlluminateRestart: 1, 
    IlluminateTracker: 1,
    IlluminateAlt: 1,
    IlluminateVel: 1,
    Brightness: 127,
    IntegralBrightness: 127,
    Standby: false
}

export const OFF_TEST = {
    IlluminateCompLight: false,
    ProgramD1: '',
    ProgramD2: '',
    VerbD1: '',
    VerbD2: '',
    NounD1: '',
    NounD2: '',
    Register1Sign:'',
    Register1D1: '',
    Register1D2: '',
    Register1D3: '',
    Register1D4: '',
    Register1D5: '',
    Register2Sign:'',
    Register2D1: '',
    Register2D2: '',
    Register2D3: '',
    Register2D4: '',
    Register2D5: '',
    Register3Sign:'',
    Register3D1: '',
    Register3D2: '',
    Register3D3: '',
    Register3D4: '',
    Register3D5: '',
    IlluminateUplinkActy: 0, 
    IlluminateNoAtt: 0,
    IlluminateStby: 0,
    IlluminateKeyRel: 0,
    IlluminateOprErr: 0, 
    IlluminateNoDap: 0,
    IlluminatePrioDisp: 0,
    IlluminateTemp: 0,
    IlluminateGimbalLock: 0,
    IlluminateProg: 0,
    IlluminateRestart: 0, 
    IlluminateTracker: 0,
    IlluminateAlt: 0,
    IlluminateVel: 0,
    Brightness: 127,
    IntegralBrightness: 127,
    Standby: false
}

export const AUDIO_LOAD = {
    IlluminateCompLight: false,
    ProgramD1: '',
    ProgramD2: '',
    VerbD1: '',
    VerbD2: '',
    NounD1: '',
    NounD2: '',
    Register1Sign:'',
    Register1D1: '',
    Register1D2: '',
    Register1D3: '',
    Register1D4: '',
    Register1D5: '',
    Register2Sign:'',
    Register2D1: 'A',
    Register2D2: 'U',
    Register2D3: 'd',
    Register2D4: 'I',
    Register2D5: 'O',
    Register3Sign:'',
    Register3D1: 'L',
    Register3D2: 'O',
    Register3D3: 'A',
    Register3D4: 'd',
    Register3D5: '',
    IlluminateUplinkActy: 0, 
    IlluminateNoAtt: 0,
    IlluminateStby: 0,
    IlluminateKeyRel: 0,
    IlluminateOprErr: 0, 
    IlluminateNoDap: 0,
    IlluminatePrioDisp: 0,
    IlluminateTemp: 0,
    IlluminateGimbalLock: 0,
    IlluminateProg: 0,
    IlluminateRestart: 0, 
    IlluminateTracker: 0,
    IlluminateAlt: 0,
    IlluminateVel: 0,
    Brightness: 127,
    IntegralBrightness: 127,
    Standby: false
}

export const NO_CONN = {
    IlluminateCompLight: false,
    ProgramD1: '',
    ProgramD2: '',
    VerbD1: '',
    VerbD2: '',
    NounD1: '',
    NounD2: '',
    Register1Sign:'',
    Register1D1: '',
    Register1D2: '',
    Register1D3: '',
    Register1D4: '',
    Register1D5: '',
    Register2Sign:'',
    Register2D1: 'n',
    Register2D2: 'O',
    Register2D3: '',
    Register2D4: '',
    Register2D5: '',
    Register3Sign:'',
    Register3D1: 'C',
    Register3D2: 'O',
    Register3D3: 'n',
    Register3D4: 'n',
    Register3D5: '',
    IlluminateUplinkActy: 0, 
    IlluminateNoAtt: 0,
    IlluminateStby: 0,
    IlluminateKeyRel: 0,
    IlluminateOprErr: 0, 
    IlluminateNoDap: 0,
    IlluminatePrioDisp: 0,
    IlluminateTemp: 0,
    IlluminateGimbalLock: 0,
    IlluminateProg: 0,
    IlluminateRestart: 0, 
    IlluminateTracker: 0,
    IlluminateAlt: 0,
    IlluminateVel: 0,
    Brightness: 127,
    IntegralBrightness: 127,
    Standby: false
}

export const NO_CONN_UHOH = {
    IlluminateCompLight: false,
    ProgramD1: '',
    ProgramD2: '',
    VerbD1: 'U',
    VerbD2: 'H',
    NounD1: 'O',
    NounD2: 'H',
    Register1Sign:'',
    Register1D1: '',
    Register1D2: '',
    Register1D3: '',
    Register1D4: '',
    Register1D5: '',
    Register2Sign:'',
    Register2D1: 'n',
    Register2D2: 'O',
    Register2D3: '',
    Register2D4: '',
    Register2D5: '',
    Register3Sign:'',
    Register3D1: 'C',
    Register3D2: 'O',
    Register3D3: 'n',
    Register3D4: 'n',
    Register3D5: '',
    IlluminateUplinkActy: 0, 
    IlluminateNoAtt: 0,
    IlluminateStby: 0,
    IlluminateKeyRel: 0,
    IlluminateOprErr: 0, 
    IlluminateNoDap: 0,
    IlluminatePrioDisp: 0,
    IlluminateTemp: 0,
    IlluminateGimbalLock: 0,
    IlluminateProg: 0,
    IlluminateRestart: 0, 
    IlluminateTracker: 0,
    IlluminateAlt: 0,
    IlluminateVel: 0,
    Brightness: 127,
    IntegralBrightness: 127,
    Standby: false
}
