/**
 * Sudoku — server-side generation and game logic. Pure state functions, no tick.
 *
 * Input model (digits 2/4/6/8 can't double as both move + entry, so movement is
 * linear and digits are reserved for values):
 *   1-9      : set the current cell's value (ignored on given cells)
 *   0 / CLR  : clear the current cell
 *   + / -    : move to the next / previous cell (row-major, wraps)
 *   ENTR     : jump to the next empty cell (fast fill workflow)
 *   RSET     : back to selector (handled by the hub)
 */

import type { SudokuState, SudokuCell } from '../../../types/serverState'

const GIVENS_TARGET = 38   // ~medium difficulty; higher = easier

// --- Grid helpers ---

function emptyGrid(): number[][] {
    return Array.from({ length: 9 }, () => Array(9).fill(0))
}

function canPlace(g: number[][], r: number, c: number, v: number): boolean {
    for (let i = 0; i < 9; i++) {
        if (g[r][i] === v) return false
        if (g[i][c] === v) return false
    }
    const br = Math.floor(r / 3) * 3
    const bc = Math.floor(c / 3) * 3
    for (let dr = 0; dr < 3; dr++) {
        for (let dc = 0; dc < 3; dc++) {
            if (g[br + dr][bc + dc] === v) return false
        }
    }
    return true
}

function shuffle<T>(arr: T[]): T[] {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1))
        const tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp
    }
    return arr
}

/** Fill an empty grid with a random complete valid solution (backtracking). */
function fillGrid(g: number[][]): boolean {
    for (let i = 0; i < 81; i++) {
        const r = Math.floor(i / 9)
        const c = i % 9
        if (g[r][c] === 0) {
            for (const v of shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9])) {
                if (canPlace(g, r, c, v)) {
                    g[r][c] = v
                    if (fillGrid(g)) return true
                    g[r][c] = 0
                }
            }
            return false
        }
    }
    return true
}

/** Count solutions of a partially-filled grid, capped at `limit`. */
function countSolutions(g: number[][], limit: number): number {
    let r = -1, c = -1
    for (let i = 0; i < 81; i++) {
        const rr = Math.floor(i / 9)
        const cc = i % 9
        if (g[rr][cc] === 0) { r = rr; c = cc; break }
    }
    if (r === -1) return 1   // no empty cell -> a complete solution
    let count = 0
    for (let v = 1; v <= 9 && count < limit; v++) {
        if (canPlace(g, r, c, v)) {
            g[r][c] = v
            count += countSolutions(g, limit - count)
            g[r][c] = 0
        }
    }
    return count
}

/** Remove cells from a full solution while keeping the solution unique. */
function makePuzzle(solution: number[][], givensTarget: number): number[][] {
    const puzzle = solution.map(row => row.slice())
    let filled = 81
    for (const idx of shuffle(Array.from({ length: 81 }, (_, i) => i))) {
        if (filled <= givensTarget) break
        const r = Math.floor(idx / 9)
        const c = idx % 9
        if (puzzle[r][c] === 0) continue
        const saved = puzzle[r][c]
        puzzle[r][c] = 0
        // Removing this cell must keep the solution unique.
        const test = puzzle.map(row => row.slice())
        if (countSolutions(test, 2) !== 1) {
            puzzle[r][c] = saved   // can't remove — would create ambiguity
        } else {
            filled--
        }
    }
    return puzzle
}

function generate(): { solution: number[][]; puzzle: number[][] } {
    const solution = emptyGrid()
    fillGrid(solution)
    const puzzle = makePuzzle(solution, GIVENS_TARGET)
    return { solution, puzzle }
}

// --- State ---

function emptyCells(): SudokuCell[][] {
    return Array.from({ length: 9 }, () =>
        Array.from({ length: 9 }, () => ({ value: 0, given: false }))
    )
}

export const INITIAL_SUDOKU: SudokuState = {
    phase: 'playing',
    mode: 'move',
    board: emptyCells(),       // a real puzzle is generated by resetSudoku() on select
    solution: emptyGrid(),
    cursor: { x: 4, y: 4 },
    startedAtMs: 0,
    bestTimeSec: null,
    finalTimeSec: null,
}

export function resetSudoku(preserveBest: number | null): SudokuState {
    const { solution, puzzle } = generate()
    const board = puzzle.map(row => row.map(v => ({ value: v, given: v !== 0 })))
    return {
        phase: 'playing',
        mode: 'move',
        board,
        solution,
        cursor: { x: 4, y: 4 },
        startedAtMs: Date.now(),
        bestTimeSec: preserveBest,
        finalTimeSec: null,
    }
}

function cloneBoard(board: SudokuCell[][]): SudokuCell[][] {
    return board.map(row => row.map(cell => ({ ...cell })))
}

function moveLinear(state: SudokuState, delta: number): SudokuState {
    const idx = state.cursor.y * 9 + state.cursor.x
    const next = (idx + delta + 81) % 81
    return { ...state, cursor: { x: next % 9, y: Math.floor(next / 9) } }
}

function moveCursor2D(state: SudokuState, dx: number, dy: number): SudokuState {
    const x = Math.max(0, Math.min(8, state.cursor.x + dx))
    const y = Math.max(0, Math.min(8, state.cursor.y + dy))
    if (x === state.cursor.x && y === state.cursor.y) return state
    return { ...state, cursor: { x, y } }
}

function jumpToNextEmpty(state: SudokuState): SudokuState {
    const start = state.cursor.y * 9 + state.cursor.x
    for (let step = 1; step <= 81; step++) {
        const idx = (start + step) % 81
        const x = idx % 9, y = Math.floor(idx / 9)
        if (state.board[y][x].value === 0) return { ...state, cursor: { x, y } }
    }
    return state
}

function isSolved(board: SudokuCell[][], solution: number[][]): boolean {
    for (let y = 0; y < 9; y++) {
        for (let x = 0; x < 9; x++) {
            if (board[y][x].value !== solution[y][x]) return false
        }
    }
    return true
}

function setValue(state: SudokuState, value: number): SudokuState {
    const { x, y } = state.cursor
    if (state.board[y][x].given) return state
    if (state.board[y][x].value === value) return state
    const board = cloneBoard(state.board)
    board[y][x].value = value
    if (value !== 0 && isSolved(board, state.solution)) {
        const finalTimeSec = (Date.now() - state.startedAtMs) / 1000
        const bestTimeSec = state.bestTimeSec === null ? finalTimeSec : Math.min(state.bestTimeSec, finalTimeSec)
        return { ...state, board, phase: 'won', finalTimeSec, bestTimeSec }
    }
    return { ...state, board }
}

export function handleSudokuKey(state: SudokuState, key: string): SudokuState {
    if (state.phase === 'won') return state

    // KEY REL toggles MOVE (2/4/6/8 arrows) <-> NUM (type digits 1-9).
    if (key === 'k') return { ...state, mode: state.mode === 'move' ? 'enter' : 'move' }

    // Available in BOTH modes: CLR erases, +/- step a cell, ENTR jumps to next empty.
    if (key === 'c') return setValue(state, 0)
    if (key === '+') return moveLinear(state, 1)
    if (key === '-') return moveLinear(state, -1)
    if (key === 'e') return jumpToNextEmpty(state)

    if (state.mode === 'move') {
        if (key === '4') return moveCursor2D(state, -1, 0)
        if (key === '6') return moveCursor2D(state, 1, 0)
        if (key === '8') return moveCursor2D(state, 0, -1)
        if (key === '2') return moveCursor2D(state, 0, 1)
        return state
    }

    // NUM (enter) mode
    if (key === '0') return setValue(state, 0)
    if (/^[1-9]$/.test(key)) return setValue(state, parseInt(key))
    return state
}
